### ISSUE TITLE
Project communication

### ISSUE THREAD

**Issue by djohns451** [wafflestealer654/google-maps-3d-client#3]
We need a form of communication outside of Markdown files.

Either [Gitter](https://gitter.im/) or [Slack](https://slack.com) would work.

**Comment by kaylathedev** [comment]
Thank you for pointing this out.

I will be using the Wiki for any information that doesn't belong in the repository. As of right now, the Wiki consists of pages that show the meanings of very commonly used functions.

~~If I feel that discussion is needed, I'll be opening a public channel on Slack.~~

Edit: Nevermind, I will be opening a public channel this weekend. Probably Saturday or Sunday.
